import Groq from "groq-sdk";
import { GROQ_API_KEY } from "../../config/env.js";
import taskSchema from "../../schemas/taskSchema.js";
import { ApiError } from "../../utils/ApiError.js";

let groq = null;

if(GROQ_API_KEY){
    groq = new Groq({ apiKey: GROQ_API_KEY });
}

const validateTaskSchema = (task) => {
    try {
        taskSchema.createTask.parse(task);
    } catch (error) {
        throw new Error("invalid task schema generated by AI")
    }
}

const generateTaskObject = async (userCommand) => {
    try {
        if(!groq){
            throw new ApiError(500, "groq api key not provided, ai feature disabled");
        }
        const currentDateTime = new Date();

        const structuredResponse = await groq.chat.completions.create({
            model: "llama-3.1-8b-instant",
            messages: [
                {
                    role: "system",
                    content: `
                        You are an AI assistant for a voice-enabled task manager.

                        Convert the user's sentence into a valid JSON object that matches EXACTLY this schema:

                        {
                            "title": string,
                            "description: string,
                            "priority": "low" | "high",
                            "dueDate": "YYYY-MM-DD"
                        }

                        Rules:
                        - Always return ONLY a raw JSON object (no markdown, no quotes, no explanations).
                        - The title must be a short.
                        - Description should be based on user input and descriptive.
                        - Priority must be inferred from words:
                        - "urgent", "important", "asap" → "high"
                        - "whenever", "optional", "later" → "low"
                        - Convert natural language dates to proper format YYYY-MM-DD, please use this ${currentDateTime} as current time.
                        - If no date is mentioned, set dueDate to today’s date.
                        - Never return null or undefined values.
                    `
                },
                {
                    role: "user",
                    content: userCommand
                }
            ],
            temperature: 0
        });


        const jsonString = structuredResponse.choices[0].message.content;

        if (!jsonString) throw new Error("LLM did not return JSON");

        const cleanJson = jsonString.replace(/```json/g, "").replace(/```/g, "").trim();

        const taskData = JSON.parse(cleanJson);

        validateTaskSchema(taskData);

        return taskData;
    } catch (error) {
        throw error;
    }
}


export default { generateTaskObject }